### ISSUE TITLE
Missing commit history

### ISSUE THREAD

**Issue by AsdMonio** [montanadevelopment-archive/android_device_motorola_montana#3]
The device tree is missing the full version history on all branches. This is also true for the vendor tree. The trees are based on the msm8953 common trees at [Motorola-Common](https://github.com/Motorola-Common). This is discrediting the contributors and is the reason for LineageOS for montana being taken down.

There are new trees on my account which have been (hopefully) properly de-commonized and I integrated some of the changes from the trees at montanadevelopment into them. At the moment the Oreo branch works the same as the old trees. I have not managed to fully boot Pie yet because of userdata encryption issues but they should be resolved soon and both branches should be functionally the same.

I'm not sure how to get this fixed aside from just cherry-picking the changes from the montanadevelopment trees into mine and then force-pushing to montanadevelopment repos, overwriting the branches (or creating new branches and deleting the bad ones later).

This is also why I'm not working on SELinux now, I think this should be resolved first.

**Comment by JarlPenguin** [comment]
I suppose the updated repositories with the commit history could go here:
https://github.com/montanadevelopment/device_motorola_montana
https://github.com/montanadevelopment/proprietary_vendor_motorola_montana

**Comment by JarlPenguin** [comment]
> At the moment the Oreo branch works the same as the old trees.
>

This means they are functionally the same as the device trees here?

> or creating new branches and deleting the bad ones later
>

This is probably the best choice in my opinion.

> The device tree is missing the full version history on all branches.
>

As in the commit history before the "Uploading" commit by ericrutgers, am I correct? 

Also I've heard that as soon as @rayslash gets a Montana, he will start making a device tree from scratch.

**Comment by AsdMonio** [comment]
> As in the commit history before the "Uploading" commit by ericrutgers, am I correct?

Yes, there are also some other issues like some missing files also imported without history or a few commits which should be cherry-picks but are not. This has all been resolved in the new trees.

> This means they are functionally the same as the device trees here?

Pretty much, I did a quick test of everything (RIL, camera, sensors, fingerprint scanner) and it seems to work fine. The USB tethering bug is still there and I cherry-picked the USB audio fix but I could not test it (don't have any USB audio devices). Besides the commit history I only re-ordered some stuff in the makefiles and made a few changes to the overlays and NFC configs. I also don't currently have all of the commits starting from https://github.com/montanadevelopment/android_device_motorola_montana/commit/75ac71c558b8f52c503f01233a02dd1faec40751 in Oreo and https://github.com/montanadevelopment/android_device_motorola_montana/commit/6c05fbc7b5fc4050aa92d563767452ae4cdced6b in Pie.

>I suppose the updated repositories with the commit history could go here

I'll push to those repos, I just managed to boot Pie with encryption but it uses a fix in the LineageOS vendor which has not been merged yet.

**Comment by JarlPenguin** [comment]
So device tree done... Now for vendor

By the way, do you have any other means of communication other than GitHub?

Edit: Cherry picked all important commits from this tree back to the other tree.

**Comment by AsdMonio** [comment]
Great, this can be closed now and we should all switch to using the new trees.

I have also re-made the kernel repositories ([msm8953-common](https://github.com/AsdMonio/android_kernel_motorola_msm8953-common) for Oreo and [msm8937](https://github.com/AsdMonio/android_kernel_motorola_msm8937) for Pie). The old repos had some problems with the commit history as well because of my attempt to use the camera driver from the LOS Nougat kernel. Now I've figured out a way to make the original driver work and it's just a config change. Should I push to a new branch or make a new repo?

For communication nowadays I mostly use Discord (AsD Monio#2121).

**Comment by JarlPenguin** [comment]
> Should I push to a new branch or make a new repo?
>

I think you should make a new repo (kernel_motorola_msm8937).

> For communication nowadays I mostly use Discord (AsD Monio#2121).
>

Alright, I'll add you on Discord.
